### ISSUE TITLE
Norka doesn't start

### ISSUE THREAD

**Issue by marco4mp** [TenderOwl/Norka#66]
Hi! Norka doesn't start.

Version: 1.0.0
AppCenter
elementary 6.1

When I put the command "flatpak run com.github.tenderowl.norka" it shows:

```
Gtk-Message: 11:31:21.308: Failed to load module "canberra-gtk-module"
/app/lib/python3.9/site-packages/norka/main.py:63: Warning: ../glib/goption.c:2448: ignoring no-arg, optional-arg or filename flags (32) on option of arg-type 1 in entry (null):new
  self.add_main_option('new', 110, GLib.OptionFlags.OPTIONAL_ARG, GLib.OptionArg.STRING,
Traceback (most recent call last):
  File "/app/bin/com.github.tenderowl.norka", line 61, in <module>
    sys.exit(main.main(REVISION))
  File "/app/lib/python3.9/site-packages/norka/main.py", line 232, in main
    app = Application(version=version)
  File "/app/lib/python3.9/site-packages/norka/main.py", line 77, in __init__
    storage_path = os.path.join(self.base_path, STORAGE_NAME)
AttributeError: 'Application' object has no attribute 'base_path'
```

**Comment by amka** [comment]
Oh, snap. I will investigate it ASAP. Thank you for the report.

**Comment by marco4mp** [comment]
Now with the new version 1.0.1 it works fine!  👍
